Traceback (most recent call last):
  File "mpi3.py", line 2, in <module>
    import cv2			        # IMPORT 'cv2' LIBRARY TO WORK WITH IMAGES
ModuleNotFoundError: No module named 'cv2'
Traceback (most recent call last):
  File "mpi3.py", line 2, in <module>
    import cv2			        # IMPORT 'cv2' LIBRARY TO WORK WITH IMAGES
ModuleNotFoundError: No module named 'cv2'
Traceback (most recent call last):
  File "mpi3.py", line 2, in <module>
    import cv2			        # IMPORT 'cv2' LIBRARY TO WORK WITH IMAGES
ModuleNotFoundError: No module named 'cv2'
Traceback (most recent call last):
  File "mpi3.py", line 2, in <module>
    import cv2			        # IMPORT 'cv2' LIBRARY TO WORK WITH IMAGES
ModuleNotFoundError: No module named 'cv2'
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[10510,1],3]
  Exit code:    1
--------------------------------------------------------------------------
